### ISSUE TITLE
What does "BGM data is too large for game" mean?

### ISSUE THREAD

**Issue by BobberyTheSailor** [bates64/mamar#69]
So you see, I am trying to test some TTYD music into PM64 and it throws this:
Error: Encoded BGM data is too large for game engine to handle at HP (https://mamar.bates64.com/app/index.61fac8af.js:1:814073) at https://mamar.bates64.com/app/index.61fac8af.js:1:815036 at hs (https://mamar.bates64.com/app/index.61fac8af.js:1:103284) at Nu (https://mamar.bates64.com/app/index.61fac8af.js:1:123416) at https://mamar.bates64.com/app/index.61fac8af.js:1:122158 at Mu (https://mamar.bates64.com/app/index.61fac8af.js:1:122223) at _u (https://mamar.bates64.com/app/index.61fac8af.js:1:115979) at ni (https://mamar.bates64.com/app/index.61fac8af.js:1:56707) at https://mamar.bates64.com/app/index.61fac8af.js:1:122218 at Mu (https://mamar.bates64.com/app/index.61fac8af.js:1:122223)
Is it because of too much instruments? The MIDI exceeding the limit? Or other?

**Comment by bates64** [comment]
It means you have too many notes in your MIDI. Try making the song less complex, or making it shorter.
